export const CONSTANT_MSG = {
    ID_OK: "Sucessfully fetched the ID",
    INTERNAL_SERVER_ERR: "Internal Server Error",
    LIST_OK: "Sucessfully fetched the list",
    FETCH_LIST_ERROR: "Error while fetching the list",
    API_ERROR: "Error in the api",
    IMPROPER_EMAIL_OR_PASSWORD: "Please check your email and password",
    USER_NOT_FOUND: "Unable to find the user",
    LOGIN_ERROR: "Error while logging in user",
    LOGIN_SUCCESS: "User Logged in Successfully",
    REGISTER_SUCCESS: "User Registered Successfully",
    USER_ALREADY_REGISTERED: "User is already registered",
    DEVICE_CREATED_SUCCESSFULLY: 'Device created successfully',
    REGISTER_ERROR: "Error while registering",
    DEVICE_CREATE_ERROR: "Error while creating device",
    UNABLE_TO_REGISTERED_DEVICE: "Unable to registered Device",
    DEVICE_ALREADY_REGISTERED: "Device id is  already registered",
    CARD_CREATE_ERROR: "Error while creating card",
    UNABLE_TO_CREATE_CARD: "Unable to create Card",
    USER_ID_NOT_FOUND: "User not found",
    Template_ID_NOT_FOUND: "Template not found",
    TEMPLATE_UPDATED_SUCCESSFULLY: 'Template updated successfully',
    TEMPLATE_DELETED_SUCCESSFULLY: 'Template deleted successfully',
    TEMPLATE_CREATED_SUCCESSFULLY: 'Template created successfully',

    TEMPLATE_CREATE_ERROR: "Error while creating Template",
    UNABLE_TO_CREATE_TEMPLATE: "Unable to create Template",
    DUPLICATE_kEY: "Template with name already exists",
    UNABLE_TO_UPDATE_TEMPLATE: "Unable to update template",
    REPORT_GENERATED_SUCCESFULLY: "Report Generated Successfully",
    UNABLE_TO_GENERATE_REPORT: "Error while creating Report",
    DAY_NOT_ALLOWED: "For daySummary, fromDate and toDate must be the same",
    STATE_NOT_FOUND: "State with name doesn't exists",
    COUNTRY_NOT_FOUND: "Country with name doesn't exists",
    Client_CREATED_SUCCESSFULLY: "client register successfully ",
    UNABLE_TO_CREATE_Client: "unable to create client",
    Client_NOT_FOUND: "client not found",
    FAILED_TO_GET_DETAIL: "failed to get device details",
    RID_NOT_DEFINED: "Rid id not defined",
    FETCH_ERROR: "error while retrieving",
    ERROR_SAVING: "error while saving",
    DEVICE_REGISTERED_SUCCESSFULLY: 'Device registered successfully',
    RID_EXIST: 'rid already exist',
    FAILED_TO_ADD_RID: 'failed to add rid',
    FAILED_TO_ADD_CONFIG: 'failed to add configurtion',
    ID_NOT_FOUND: 'id not found',
    FAILED_TO_UPDATE_CONFIG: 'failed to update config',
    CONFIG_UPDATED: 'config updated successfully',
    ADDED_CONFIG: 'config added successfully',
    FAILED_TO_ADD_CONNECTION: 'failed to add connection between rid and config',
    CONNECTION_ADDED_SUCCESSFULLY: 'connection added between rid and config',
    FAILED_TO_REMOVE_DEVICE_CONNECTION: 'failed to removed rid device connnection',
    SUCCESFULLY_REMOVED_DEVICE_CONNECTION: 'successfully removed rid devic conneciton',
    FAILED_TO_RECONFIGURE: 'failed to reconfigure device',
    FAILED_TO_ADD_CONFIGURATAION_DETAILS: 'failed to add configuration details',
    SUCCESSFULLY_ADDED_RECONFIGURATION_DETAILS: 'failed to add reconfiguration details',
    FAILED_TO_ADD_RECONFIG_DETAILS: 'Successfully added reconfiguration config details',
    ADDED_RECONFIG_DETAILS: 'Fail to insert into reconfiguration config table',
    SUCCESSFULLY_RECONFIG: 'successfully reconfigured',
    FAILED_TO_DELINK_RID_AND_DEVICE: 'failed to delink rid and device',
    FLOW_FORMULA_NOT_ADDED: 'flow formula not added successfully',
    SUCCESSFULLY_FLOW_FORMULA_ADDED: 'successfully flow formula added',
    F_CODE_ALREADY_EXIST: 'f_code already exist',
    FLOW_FORMULA_NOT_FOUND: 'flow formula not found',
    SUCCESSFULLY_UPDATED: 'succssfully updated flow formula',
    FAILED_TO_GET_FLOW_FORMULA: 'failed to get flow formula',
    ADDED_STATE_SUCCESSFULLY: 'added state successfully',
    ADDED_STATE_UNSUCCESSFULLY: 'added state unsuccessfully',
    VENDOR_SAVED_UNSUCCESSFULLY: 'unable to saved vendor',
    VENDOR_SAVED_SUCCESSFULLY: 'vendor saved successfully',
    FETCH_SUCCESSFULLY: 'fetch successfully',
    RECEIVED_TOKEN_SUCCESSFULLY: 'received token successfully',
    UNSUCCESSFULLY_TOKEN: 'enable to received token',
    ADDED_THING_SUCCESSFULLY: 'added thing successfully',
    UNADDED_THINGS: 'unable to add thing',
    ADDED_CHANNEL_SUCCESSFULLY: 'added channel successfully',
    UNABLE_TO_ADD: 'unable to add channel ',
    SUCCESSFULL: 'successfull',
    UNSUCCESSFULL: 'unsuccessfull',
    CONNECTED: 'connect',
    NO_CONTENT: 'no content',
    SUCCESSFULLY_ADDED_DEVICE: 'succesfully added the device',
    FAILED_TO_ADD_DEVICE: 'failed to add device',
    SUCCESSFULLY_UPDATED_RID_DEVICE_ENTRY: 'successfully updated rid device entry',
    SUCCESSFULLY_INSERT_RID_DEVICE_ENTRY: 'successfully insert rid device entry',
    FAILED_TO_CONNECT_DEVICE: 'failed to connect device',
    FAILED_TO_GENERATE_FLUX_CREDENTIALS: 'failed to generat flux credentials',
    FAILED_TO_GET_RID_DEVICE_CONNECTION_DETAILS: 'failed to get rid device connection details',
    FAILED_TO_ADD_RID_no: 'failed to add RID_no',
    SUCCESSFULLY_DEVICE_REGISTERED: 'successfully device registered',
    FAILED_TO_REMOVED: 'failed to remove',
    SUCCESSFULLY_REMOVED: 'successfully removed',
    FAILED_TO_ADD_CONFIGURATAION: 'failed to add configurtaion',
    FAILED_TO_CONFIGURE_DEVICE: 'failed to configure device',
    SUCCESSFULLY_RECONFIGURED: 'successfully reconfigured',
    FAIL_TO_UPDATE_DEVICE: 'failed to update device',
    FAIL_TO_ADD_FLOW_FORMULA: 'fail to add flow formula',
    ERROR_WHLE_ADDUPDATECONFIGURATION: 'error while addUpdateConfiguration',
    DEVICE_ALREADY_EXISTS: 'device already exist',
    IMEI_OK: "successfully retrieve imei",
    IMEI_NOT_FOUND: "imei not found",
    SAME_RID: 'same rid',
    TRIED_TO_UPDATE_DEVICE_WITH_NEW_RID: 'tried to update device with new rid',
    FAILED_TO_INSERT_RID_DEVICE_ENTRY: 'failed to insert rid device entity',
    FAILED_TO_UPDATE: 'failed to update',
    SUCCESSFULLY_DEVICE_UPDATED: 'successfully device updated',
    SUCCESFULLY_REMOVED_DEVICE: 'successfully removed the device',
    SUCCESFULLY_REMOVED_RID_DEVICE: 'successfully removed rid device',
    ID_DELETED_SUCCESSFULLY: 'ref_id deleted successfully',
    RID_UPDATED_SUCCESSFULLY: 'rid updated successfully',
    STATE_ALREADY_EXIST: 'state already exist',
    FAILED_TO_UPDATE_STATE: 'failde to update state',
    UPDATE_STATE_SUCCESSFULLY: 'update state successufully',
    ERROR_WHILE_DELETING: 'error while deleting',
    RETRIEVE_SUCCESSFULLY: 'retrive successfully',
    VENDOR_ALREADY_EXIST: 'vendor already exist',
    UNABLE_TO_ADD_VENDOR: 'unable to add vendor',
    STATE_DOES_NOT_EXIST: 'state does not exist',
    UNABLE_TO_UPDATE: 'unable to update vendor',
    VENDOR_UPDATED_SUCCESSFULLY: 'vendor updated successfully',
    ENABLE_TO_ADD_SIM: 'enable to add sim',
    SIM_ADDED_SUCCESSFULLY: 'sim added successfully',
    ID_EXIST: 'Already Exist',
    UNABLE_TO_ADD_RID_SIM: 'unable to add rid and sim',
    ACCEPTED: 'accepted',
    RID_SIM_UPDATED: 'update in rid_ref_id',
    SIM_UPDATED: 'updated the sim successfully',
    ERROR_WHILE_UPDATING: 'error while updating',
    CONFIGURATION_SUCCESS: 'configuration success',
    FAIL_TO_CONFIGUARTION: 'fail to configuartion',
    FAIL_TO_CONFIG: 'fail to config',
    FAIL_TO_CHECK_RID_CONFIG_RELATION: 'fail to check rid config relation',
    RID_DOES_NOT_EXIST: 'rid does not exist',
    FAIL_TO_CHECK_RID_EXIST_OR_NOT: 'fail to check rid exist or not',
    MOTOR_TYPE_IS_INVALID: 'motor type is invalid',
    CONFIG_UPDATED_SUCCESSFULLY: 'config update successssfikky',
    ERROR_WHILE_UPDATING_CONFIG: 'error while updating config',
    CONFIG_SAVED_SUCCESSFULLY: 'config saved successfully',
    AGENCY_ADDED_SUCCESSFULLY: 'agency added successfully',
    SUCCESSFULLY_UPDATED_AGENCY: 'successfully updated agency',

    RETRIEVED_FLOW_FORMULA_DATA: 'retrieved flow formula data',
    RETRIVED_CONFIG_DATA_SUCCESSFULLY: 'retrieved config data successfully',
    NOT_ABLE_TO_RETRIVED_CONFIG_DATA_SUCCESSFULLY: 'not able to retrived config data successfully',
    NOT_ABLE_TO_UPDATE_CONFIG_DATA_SUCCESSFULLY: 'not able to update config data sucessfully',
    ABLE_TO_UPDATE_CONFIG_DATA_SUCCESSFULLY: 'able to update data successfully',
    AGENCY_ALREADY_EXISTS: 'agency already exists',
    FAILED_TO_ADD_AGENCY_DETAILS: 'failed to add agemcy details',
    BAD_REQUEST: 'bad request',
    ABLE_TO_GET_AGENCY_BY_NAME: 'able to get agency by name'
    , NOT_ABLE_TO_GET_AGENCY_BY_ITS_NAME: 'not able to get agency by its name',
    GET_AGENCIES_DETAILS_SUCCESSFULLY: "able to get agencies detail successfully",
    UNABLE_TO_UPDATE_AGENCY: 'unable to update agency',
    SUCCESSFULLY_DELETED_AGENCY_DETAILS: ' deleted agency details successfully',
    FAIL_TO_DELETE: 'fail to delete',
    FAILED_TO_ADD: 'failed to add',
    SUCCESSFULLY_ADDED: 'successfully added',
    CONTROLLER_ALREADY_EXIST: 'controller already exists',
    ABLE_TO_UPDATE_CONTROLLER: 'able to update controller',
    FAIL_TO_UPDATE: 'fail to update',
    FAIL_TO_DELETE_CONFIG: 'able to delete config',
    SUCCESSFULLY_DELETED_CONFIG: 'successfully deleted config',
    CONTROLLER_UPDATED_SUCCESSFULLY: 'controller updated successfully',
    REF_ID_DOES_NOT_PRESENT: 'ref_id does not present',
    GET_OEM_DETAILS: 'get oem details',
    FAILED_TO_GET_OEM_DETAILS: 'failed to get oem details',
    OEM_ALREADY_EXIST: 'oem already exist',
    FAIL_TO_ADD: 'Ffail to add',
    NOT_FOUND_REF_ID: 'not found ref id',
    FAILED_TO_DELETE_OEM: 'failed to delete oem',
    SUCCESSFULLY_DELETED_OEM: 'successfully deleted oem',
    UPDATED_OEM_SUCCESSFULLY: 'updated oem successfully',
    NOT_ABLE_TO_UPDATE_OEM: 'not able to update oem',
    PROJECT_SAVED_SUCCESSFULLY:'project saved successfully',
   PROJECT_ALREADY_EXIST:'project already exists',
    PROJECT_UPDATED_SUCCESSFULLY:'project updated successfully',
    PROJECT_DELETED_SUCCESSFULLY:'project deleted successfully',
    NOT_ABLE_TO_GET_MODEL:'not able to get model',
    ABLE_TO_GET_MODEL:'able to get model',
    PUMP_MODEL_ALREADY_EXIST:'pump model already exist',
    ADDED_PUMP_MODEL_SUCCESSFULLY:'added pump model successfully',
    FAILED_TO_ADD_PUMP_MODEL:'failed to add pump model',
    SOLARPUMP_ALREADY_EXIST:'solarPump_already exists',
    SOLARPUMP_UPDATED_SUCCESSFULLY:'solar pump updated successfully',
    SOLARPUMP_DELETED_SUCCESSFULLY:'solar pump deleted successfully',
     ALREADY_EXIST:'already exist',
    SOLARPUMP_SAVED_SUCCESSFULLY:'solar pump saved successfully',
    PUMPHEAD_ALREADY_EXIST:'pumphead already exist',
    PUMPHEAD_DELETED_SUCCESSFULLY:'pump head deleted successfully',
    PUMPHEAD_UPDATED_SUCCESSFULLY:'pump head updated successfully',
    PUMPHEAD_SAVED_SUCCESSFULLY:'pump head saved successfully',
    MOTOR_ALREADY_EXIST:'motor already exist',
   MOTOR_SAVED_SUCCESSFULLY:'motor saved successfully',
   MOTOR_UPDATED_SUCCESSFULLY:'motor updated successfully',
   MOTOR_DELETED_SUCCESSFULLY:'motor deleted successfully',
   OEM_SAVED_SUCCESSFULLY:'oem saved successfully',
   OEM_UPDATED_SUCCESSFULLY:'oem updated successfully',
   CONTROLLER_SAVED_SUCESSFULLY:'controller saved successfully',
   CONTROLLER_NOT_FOUND:'controller not found',
   PUMPCODE_ALREADY_EXIST:'pumpcode already exists',
   PUMPCODE_SAVED_SUCCESSFULLY:'pump code saved successfully',
   PUMPCODE_UPDATED_SUCCESSFULLY:'pump code saved successfully',
   FARMER_ADDED_SUCCESSFULLY:'farmer added successfully',
   NOT_ABLE_TO_GET_PROJECT_DETAILS:'not able to get project details',
   RETRIEVED_PROJECT_DETAILS_SUCCESSFULLY:'retrieved project details successfully',
   UPDATED_PROJECT_DETAILS_SUCCESSFULLY:'updated project details successfully',
   RETRIEVED_PUMP_SITE_DATA:'retrieved pump site data',
   PUMP_SITE_ADDED_SUCCESSFULLY:'pump site added successfully',
   FAILED_PUMP_SITE_DATA:'failed pump site data ',
   FAILED_RETRIEVING_PUMP_SITE_DATA:'failed retrieving pump site data',
   FAILED_TO_RETRIEVE_PUMP_SITE_DATA:'fail to retrieve pump site data',
   UPDATED_PUMP_SITE_SUCCESSFULLY:'updated pump site successfully',
   FAIL_TOADD_USER:'fail to add user',
   USER_ADDED_SUCCESSFULLY:'user added sucessfully',
   EMAIL_NOT_EXIST:'email not exist',
   EMAIL_NOT_FOUND:'email not found ',
   FOUND_EMAIL:'found email',
   RETRIEVED_USER_DETAILS_SUCCESSFULLY:'retrieved user detalis successfully',
   FAIL_TO_RETRIEVE_USER_DETAILS:'fail to retrieve user details successfully',
   FAIL_TO_UPDATE_USER:'fail to update user ',
   UPDATED_USER_SUCCESSFULLY:'updated user successfully',
   USER_DELETED_SUCCESSFULLY:'user deleted successfully',
   FAILED_TO_DELETE_USER:'failed to delete user',
   USER_DOES_NOT_EXIST:'user does not exist',
   PASSWORD_DOES_NOT_MATCH:'password does not match',
   FAIL_TO_ADD_USER_PERMISSION:'failed to add user permission',
   ADDED_USER_PERMISSION:'added user permission',
   RETRIEVED_USER_PERMISSION_DETAILS_SUCCESSFULLY:'retrived user_permission details successfully',
   FAIL_TO_RETRIEVE_USER_PERMISSION_DETAILS:'fail to retreieve user permission details',
   FAILED_TO_RETREIVE_USER_RID_DETAILS:'failed to retreive user_rid details',
   RETREIVED_USER_RID_DATA_SUCCESSFULLY:'retreived user rid data successfully'










}