export const CONSTANT_MSG = {
  ID_OK: 'Sucessfully fetched the ID',
  INTERNAL_SERVER_ERR: 'Internal Server Error',
  LIST_OK: 'Sucessfully fetched the list',
  FETCH_LIST_ERROR: 'Error while fetching the list',
  API_ERROR: 'Error in the api',
  IMPROPER_EMAIL_OR_PASSWORD: 'Please check your email and password',
  USER_NOT_FOUND: 'Unable to find the user',
  LOGIN_ERROR: 'Error while logging in user',
  LOGIN_SUCCESS: 'User Logged in Successfully',
  REGISTER_SUCCESS: 'User Registered Successfully',
  USER_ALREADY_REGISTERED: 'User is already registered',
  DEVICE_CREATED_SUCCESSFULLY: 'Device created successfully',
  REGISTER_ERROR: 'Error while registering',
  DEVICE_CREATE_ERROR: 'Error while creating device',
  UNABLE_TO_CREATE_DEVICE: 'Unable to create Device',
  DEVICE_ALREADY_REGISTERED: 'Device id is  already registered',
  CARD_CREATE_ERROR: 'Error while creating card',
  UNABLE_TO_CREATE_CARD: 'Unable to create Card',
  USER_ID_NOT_FOUND: 'User not found',
  Template_ID_NOT_FOUND: 'Template not found',
  TEMPLATE_UPDATED_SUCCESSFULLY: 'Template updated successfully',
  TEMPLATE_DELETED_SUCCESSFULLY: 'Template deleted successfully',
  // Field_UPDATED_SUCCESSFULLY: 'Fi updated successfully',
  // Field_DELETED_SUCCESSFULLY: 'Template deleted successfully',
  TEMPLATE_CREATED_SUCCESSFULLY: 'Template created successfully',

  TEMPLATE_CREATE_ERROR: 'Error while creating Template',
  UNABLE_TO_CREATE_TEMPLATE: 'Unable to create Template',
  DUPLICATE_kEY: 'Template with name already exists',
  UNABLE_TO_UPDATE_TEMPLATE: 'Unable to update template',
  REPORT_GENERATED_SUCCESFULLY: 'Report Generated Successfully',
  UNABLE_TO_GENERATE_REPORT: 'Error while creating Report',
  DAY_NOT_ALLOWED: 'For daySummary, fromDate and toDate must be the same',
  STATE_NOT_FOUND: "State with name doesn't exists",
  COUNTRY_NOT_FOUND: "Country with name doesn't exists",
  Client_CREATED_SUCCESSFULLY: 'client register successfully ',
  UNABLE_TO_CREATE_Client: 'unable to create client',
  Client_NOT_FOUND: 'client not found',
  IMEI_OK: 'successfully retrieve imei',
  IMEI_NOT_FOUND: 'imei not found',
  SUCCESSFULLY_UPDATED_AGENCY:'successfully updated agency',
  UPDATED_OEM_SUCCESSFULLY:'updated oem successfully',
  NOT_ABLE_TO_UPDATE_OEM:'not able to update oem',
  PROJECT_SAVED_SUCCESSFULLY:'project saved successfully',
  PROJECT_ALREADY_EXIST:'project already exists',
   PROJECT_UPDATED_SUCCESSFULLY:'project updated successfully',
   PROJECT_DELETED_SUCCESSFULLY:'project deleted successfully',
   TOKEN_GENERATED_SUCCESSFULLY:'token generated successfully',
   INVALID_CREDENTIALS:'invalid credentials'
};
